services:
  worker:
    build: .
    container_name: experiment-worker-python
    ports:
      - 6066:6066
    env_file:
      - .env
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: 3
